### ISSUE TITLE
Use combineReducers

### ISSUE THREAD

**Issue by michaelcheng924** [teamyouhired/youhired#30]
1) Change `reducers/reducers` to be a list of reducer files, like this: https://github.com/michaelcheng429/react-redux-fullstack-starter/blob/master/app/reducers/index.js

2) Create an initial `dashboard` reducer file (a simplified version of this: https://github.com/michaelcheng429/react-redux-fullstack-starter/blob/master/app/reducers/UsersReducer.js) and add it to the `reducers/reducers` file

2) Pass in `combineReducers(reducers)` instead of `reducers` (you can use this page to help: https://github.com/michaelcheng429/react-redux-fullstack-starter/blob/master/app/helpers.js)

**Comment by michaelcheng924** [comment]
Found out my steps above weren't complete. Also need to:

1) Fix reducers import to `import * as reducers from './reducers/reducers';`

**Comment by JH108** [comment]
I implemented a form of this, will look to refactor once we have more reducers.
